### PR TITLE
Dev content review

### PR DESCRIPTION
**Pull request by k-rtik**
- [x] the test output should be updated
  - SystemEndpointTest -> SystemEndpointIT
  - InventoryEndpointTest -> InventoryEndpointIT
- [x] MP 3.3 is not released yet, use 3.2 at this moment.
- [x] in pom.xml files, dependencies for `<!-- Support for JDK 9 and above -->` may not be necessary
- [x] make sure that the license year(s) for the updated test java files `*IT.java` is updated 
- [x] following import is not necessary in SystemEndpointIT
  - `import javax.json.JsonObject;`
- [x] Dockerfiles do not following the best practice 
- [x] should use `<variable/>` in server.xml
Note: make sure finish and start are updated

### CODE REVIEW

**Comment by gkwan-ibm** [comment]
@k-rtik README license years should be `2018, 2020` not `2018, 2019, 2020`

**Comment by k-rtik** [comment]
relevant issues: #73 #69

**Comment by NimG98** [comment]
- [ ] Don't need `final` for variable in IT files

**Comment by NimG98** [comment]
### Creating a Kubernetes cluster on IBM Cloud
- [ ] `ibmcloud ks cluster-create --name guide-cluster` command doesn't work
    - I updated to newest versions:
    ```
    ibmcloud version 0.22.1+66bb68d-2020-02-28T07:50:09+00:00

    ~/Downloads » ibmcloud plugin list 
    Listing installed plug-ins...
    Plugin Name                                               Version
    container-registry                                      0.1.454      
    container-service/kubernetes-service   1.0.0
    
    ```

**Pull request merged**
